# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.
# Change python version to one thats appropriate for your application.
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
 
## Create a new Azure repo and below file in it.
pool: mypool
trigger:
  branches:
    include: 
    - master
stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: python3 -m pip install --upgrade pip setuptools wheel
    - script: pip3 install -r $(System.DefaultWorkingDirectory)/requirements.txt
    
  displayName: 'Build'
    
        
- stage: Test
  jobs:
  - job: RunTestwithTox
    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python 3.7'
        inputs:
          versionSpec: /Users/jaysengonzales/myagent/_work/_tool/Python/ 
          
      
      - script: pip3 install tox
        displayName: 'Install Tox'

      - script: tox -e py
        displayName: 'Run Tox'

- stage: Deploy
  jobs:
  
  - job: Deploy
    pool: 
      mypool
    steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1 (ec7f7f93-527d-47ba-a918-ed051b37866a)'
        appType: 'webAppLinux'
        WebAppName: 'Q2-web-app-exercise'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
        RuntimeStack: 'PYTHON|3.7'
    - task: PublishBuildArtifacts@1
    